///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LocationsModelData {
/*
{
  "location_id": 1,
  "location_name": "Branch 1"
} 
*/

  int? locationId;
  String? locationName;
  static LocationsModelData? selectedLocation;

  LocationsModelData({
    this.locationId,
    this.locationName,
  });
  LocationsModelData.fromJson(Map<String, dynamic> json) {
    locationId = json['location_id']?.toInt();
    locationName = json['location_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['location_id'] = locationId;
    data['location_name'] = locationName;
    return data;
  }
}

class LocationsModel {
/*
{
  "data": [
    {
      "location_id": 1,
      "location_name": "Branch 1"
    }
  ]
} 
*/

  List<LocationsModelData?>? data;

  LocationsModel({
    this.data,
  });
  LocationsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LocationsModelData>[];
      v.forEach((v) {
        arr0.add(LocationsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
